networking/samba
upgrades-migrations/preupgrade-assistant-modules pull request #11
Opened 2017-09-13 13:23 UTC by jmazanek

- message printed regarding the deprecation of SMB1 protocol

2017-09-14 10:24 UTC, pirat89 requested changes

2017-09-14 10:24 UTC, pirat89 commented on RHEL6_7/networking/samba/check
> +SOLUTION_FILE="./solution.txt"
Why do you create this variable for one use in echo? It is unneeded.

2017-09-14 10:24 UTC, pirat89 commented on RHEL6_7/networking/samba/check
> +echo "SMB1 protocol is deprecated as it is replaced by SMB2 protocol. It is now considered insecure, due to it's vulnerability to man-in-the-middle attacks. Support for the SMB2 protocol will not be
When the message is persistent and there is not any other check than the samba-common package available on system, the message shoud be part of the solution.txt file.

2017-09-14 10:24 UTC, pirat89 commented on RHEL6_7/networking/samba/check
> +exit $RESULT_FAIL
High risk is not needed here as the action is required on the target machine. Use rather the `log_medium_risk` instead.

2017-09-14 11:37 UTC, jmazanek commented
Module has been edited in accordance with requested changes.  Message text has been already reviewed by jhornice. Please merge

2017-09-14 16:31 UTC, pirat89 submitted a review, later dismissed
It seems OK. I'll keep it opened as changes in text are expected yet and it can be merge everytime before the next release.

2017-09-27 12:38 UTC, jmazanek commented
The link to the article discussing in detail implications of the change for the interworking with Windows based networks was added to the module

2017-09-27 15:42 UTC, pirat89 approved these changes

2017-09-27 15:43 UTC, merged