Remove legacy grub before installation of grub2
upgrades-migrations/preupgrade-assistant-modules pull request #119
Opened 2019-02-14 17:08 UTC by pirat89

The grub2-common rpm has file conflict with the grub rpm so
installation of grub2 is not possible. This occurs when rhelup
is called without the --cleanup-post option.

2019-02-14 19:23 UTC, bocekm submitted a review, later dismissed
Tested and it works.

2019-02-14 21:18 UTC, bocekm requested changes
The link to the system admin guide in the solution.txt is not working. The correct one is https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/sec-upgrading_from_grub_legacy_to_grub_2

It would actually work also if you only add underscore between grub and 2 ;)

2019-02-15 10:00 UTC, pirat89 commented
@bocekm Good catch! I am curious whether the link has been changed or whether the issues happened because of PEBKAC :)

2019-02-15 10:37 UTC, bocekm approved these changes

2019-02-15 10:39 UTC, merged