system/tuned: updated the check, added more rules
upgrades-migrations/preupgrade-assistant-modules pull request #125
Opened 2020-05-25 21:48 UTC by yarda

Related: https://projects.engineering.redhat.com/browse/OAMG-3185

Signed-off-by: Jaroslav Škarvada <jskarvad@redhat.com>

It adds more check logic. Currently the code doesn't work for profiles with spaces in the name (I am not sure whether it's supported, if yes, feel free to update the code).

It works the following way:
- it backups profiles which it doesn't recognize (i.e. profiles we don't ship)
- it backups profiles that we ship in case they were modified
- profiles that we ship are not backed up if they weren't modified
- backed up profiles needs to be hand migrated
- it maps active_profile to the known replacement profile
- if it cannot recognize the active_profile or if it is not supported, it uses the default recommended profile

Also it wouldn't be bad if it could run check after the migration (i.e. on the RHEL-7). In such case I would recommend running `tuned-adm recommend` (on the RHEL-7) and if its output differs from the $ACTIVE_PROFILE it could warn user that her or his profile is different from the recommended one and that she or he could reconsider using the recommended defaults.

2020-05-27 13:33 UTC, pirat89 requested changes
discussed in person, we will do some changes here:
- update solution.txt
- create postupgrade script
- do backup into different dirs

just putting the note here to inform that no other review is needed

Edit: to make it clear, one of original problems and still the current one, that inside the pustupgrade dir (when backup happens), if any executable is stored (from rhel 7 system), it will be processed during the post-upgrade phase. which we do not want in this case.

2020-07-09 15:11 UTC, AloisMahdal commented
Note that the stray output is #122.

2020-07-10 07:00 UTC, pirat89 commented
@yarda kind of done. I did one push force to fix some changes to fix couple of things in those two additional commits. So far it seems it works. Pls check the current solution and let me know.

2020-07-10 12:28 UTC, yarda reviewed
In overall LGTM, please address my comments (me as the original PR author cannot approve or request the changes :)

2020-07-10 12:28 UTC, yarda commented on RHEL6_7/system/tuned/zz_tuned_post.sh
> +if [ "$ACTIVE_PROFILE" != "$REC_PROFILE" ]; then
If tuned hasn't been started yet then /etc/tuned/active_profile is "" and  /etc/tuned/profile_mode is "auto", in such case the recommended profile will be automatically applied and the test should handle this case.

2020-07-10 12:28 UTC, yarda commented on RHEL6_7/system/tuned/zz_tuned_post.sh
> +if [ "$ACTIVE_PROFILE" != "$REC_PROFILE" ]; then
I.e. it shouldn't write the warning message if /etc/tuned/active_profile is "" and /etc/tuned/profile_mode is "auto"

2020-07-10 12:28 UTC, yarda commented on RHEL6_7/system/tuned/solution.txt
> +After the upgrade to Red Hat Enterprise Linux (RHEL) 7, the profiles can be migrated manually with the help of the 'tuned-man' and 'tuned-profiles' commands to the /etc/tuned/ directory.
It's `tuned` and `tuned-profiles` manual pages not commands. Also Tuned documentation (https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/performance_tuning_guide/index#chap-Red_Hat_Enterprise_Linux-Performance_Tuning_Guide-Tuned) could be mentioned.

2020-07-10 12:28 UTC, yarda commented on RHEL6_7/system/tuned/solution.txt
> +It is recommended to execute the "tuned-adm recommend" command after the upgrade on the RHEL 7 system. If the output differs from the active profile, reconsider change of the active profile to the re
Maybe this recommendation could be dropped, because this check is now automatically run in post.

2020-07-10 12:28 UTC, yarda commented on RHEL6_7/system/tuned/solution.txt
> +Customized and third party tuned profiles are backed up in 'TUNED_BACKUP_DIR'.
I would drop the old Fedora power management guide and would link the RHEL performance guide mentioned above.

2020-07-10 12:28 UTC, yarda commented on RHEL6_7/system/tuned/check
> +    if [[ ! -d "$TUNED_BACKUP_DIR" ]]; then
You could drop the `if` conditional, because `mkdir -p DIR` always succeed even if the directory exists.

2020-07-13 11:12 UTC, pirat89 submitted a review, later dismissed
lgtm. Thanks @yarda for your contribution! :)

2020-07-13 14:02 UTC, AloisMahdal commented
I ran the original downstream test with

    preupgrade-assistant-2.6.1-1.201903271312Z.master.el6_10
    preupgrade-assistant-el6toel7-0.7.9-0.202007130935Z.PR125.el6_10
    preupgrade-assistant-el6toel7-data-0.20200704-1.el6_10
    redhat-upgrade-tool-0.8.0-1.201903271313Z.rhel6.el6_10

Is this expected in upgrade.log?:

    [..]
    [..]
    Jul 13 12:11:14 (hostname) upgrade-post[31894]: Config file /var/lib/logrotate.status does not exists.
    Jul 13 12:11:14 (hostname) upgrade-post[31894]: Copy file var/lib/logrotate.status to /var/lib/logrotate.status
    Jul 13 12:11:14 (hostname) upgrade-post[31894]: Running /root/preupgrade/postupgrade.d/zz_tuned_post.sh...
    Jul 13 12:11:14 (hostname) upgrade-post[31894]: Warning: The recommended tuned profile 'throughput-performance' is different from the active one 'virtual-guest'. Consider the change of the profile.
    Jul 13 12:11:14 (hostname) upgrade-post[31894]: redhat_upgrade_tool.util WARNING: failed to remove /system-upgrade-root: [Errno 16] Device or resource busy: '/system-upgrade-root/mnt'
    Jul 13 12:11:15 (hostname) upgrade-post[31894]: resetting bootloader config
    [..]
    [..]

Asking just about the "recommended tuned profile"; the "failed to remove" is already known as upgrades-migrations/redhat-upgrade-tool#52

Otherwise no issues found; the test passed.

2020-07-13 14:12 UTC, pirat89 commented
@AloisMahdal it's expected message. The warning is additional pointer that user should check it. The same instruction is already in the preupgrade report.

2020-07-13 14:20 UTC, AloisMahdal commented
also note that this message is not in preupgrade asessment (result.html); the result there is `pass`.

2020-07-13 14:31 UTC, yarda commented
Yes, the warning about recommended profile is usually OK, but in this case it's suspicious.

In case it's virtual machine, the 'tuned-adm recommend' should recommend 'virtual-guest' profile, not the 'throughput-performance' profile. What's the output of the 'virt-what' command on the machine?

2020-07-13 16:03 UTC, AloisMahdal commented
*virt-what* produces empty output on this one.

2020-07-13 16:07 UTC, yarda commented
So it's probably OK, on bare metal (with the empty virt-what output) the recommendation to use 'throughput-performance' profile is correct.

2020-07-13 16:21 UTC, AloisMahdal commented
> Also it wouldn't be bad if it could run check after the migration (i.e. on the RHEL-7). In such case I would recommend running
> tuned-adm recommend (on the RHEL-7) and if its output differs from the $ACTIVE_PROFILE it could warn user that her or his > profile is different from the recommended one and that she or he could reconsider using the recommended defaults.

Why this?  IOW, how does having different than recommended profile relate to upgrade?

If it's because recommendations changed, could we predict that change and report the fact to the assessment?

2020-07-13 16:28 UTC, yarda commented
Theoretically we cannot predict it. Tuned on RHEL-6 doesn't have the recommend feature. On RHEL-7 the 'recommend' behaviour can be also changed by 3rd party packages.

2020-07-13 16:34 UTC, AloisMahdal commented
OK, talking to @pirat89 the intent is that user is already instructed about possible need of re-consideration.  This warning is a smart reminder of that.

However there's actually nothing about this in the assessment:

![oamg3352-ast](https://user-images.githubusercontent.com/217935/87329444-3d449780-c537-11ea-8a4e-770e29227a0f.png)

2020-07-13 18:12 UTC, AloisMahdal commented
With

    preupgrade-assistant-2.6.1-1.201903271312Z.master.el6_10
    preupgrade-assistant-el6toel7-0.7.9-0.202007131641Z.PR125.el6_10
    preupgrade-assistant-el6toel7-data-0.20200704-1.el6_10
    redhat-upgrade-tool-0.8.0-1.201903271313Z.rhel6.el6_10

the original downstream test now passed.

2020-07-14 04:59 UTC, pirat89 approved these changes

2020-07-14 04:59 UTC, pirat89 commented
Thanks guys @yarda @AloisMahdal . Merging

2020-07-14 05:00 UTC, merged