[WIP] Enable & handle uefi during the upgrade
upgrades-migrations/preupgrade-assistant-modules pull request #131
Opened 2020-07-14 13:07 UTC by pirat89

Currently it's completely broken, as UEFI related content is removed during the IPU so bootloader is broken without possibility to fix it from the uefi shell.

2020-07-14 14:45 UTC, pirat89 commented
Note: the documentation is not updated yet, to inform about manual steps after the upgrade related to EFI. It will be prepared later in the mentioned document (see the solution text)

2020-07-15 09:37 UTC, pirat89 commented
@jhlavac ping :)

2020-07-15 11:04 UTC, bocekm requested changes

2020-07-15 11:04 UTC, bocekm commented on RHEL6_7/system/uefi/check
> +  msg+=" the in-place upgrade with EFI. Install the efibootmgr rpm and run"
```suggestion
  msg="The EFI firmware has been detected but the efibootmgr utility"
  msg+=" is missing. Without the utility it is not possible to proceed with"
  msg+=" the in-place upgrade. Install the efibootmgr rpm and run"
```

2020-07-15 11:04 UTC, bocekm commented on RHEL6_7/system/uefi/check
> +log_medium_risk "The Legacy GRUB has to be migrated to GRUB 2 after the upgrad emanually"
```suggestion
log_medium_risk "The Legacy GRUB has to be migrated to GRUB 2 after the upgrade manually"
```

2020-07-15 11:04 UTC, bocekm commented on RHEL6_7/system/uefi/check
> +exit_fail
I hope the table in https://github.com/upgrades-migrations/preupgrade-assistant/wiki/How-modules-affect-the-Preupgrade-Assistant-return-code still works:
```
| exit_x         | log_x_risk    | result in XML    | return code |
|================|===============|==================|=============|
| fail           | medium        | needs_inspection |  0          |
```

2020-07-15 11:04 UTC, bocekm commented on RHEL6_7/system/uefi/module.ini
> +content_description = Set up the next boot entry correctly on EFI systems to ensure the boot in correct partition will happen after each restart during the in-place upgrade procedure.
```suggestion
content_description = Set up the next boot entry correctly on EFI systems to ensure that booting will happen in a correct partition after each restart during the in-place upgrade procedure.
```

2020-07-15 11:04 UTC, bocekm commented on RHEL6_7/system/uefi/efibootorder_fix.sh
> +# rpm, that is removed during the upgrade
```suggestion
# rpm which is removed during the upgrade
```

2020-07-15 11:04 UTC, bocekm commented on RHEL6_7/system/uefi/efibootorder_fix.sh
> +    log_info "Back up EFI files."
```suggestion
    log_info "Backing up EFI files."
```

2020-07-15 11:04 UTC, bocekm commented on RHEL6_7/system/uefi/efibootorder_fix.sh
> +    log_info "Restore EFI files."
```suggestion
    log_info "Restoring EFI files."
```

2020-07-15 11:04 UTC, bocekm commented on RHEL6_7/system/uefi/efibootorder_fix.sh
> +    log_info "Set the next boot to: $current_boot"
```suggestion
    log_info "Setting the next boot to: $current_boot"
```

2020-07-15 11:05 UTC, pirat89 commented on RHEL6_7/system/uefi/check
> +exit_fail
yes :)

2020-07-15 11:09 UTC, bocekm approved these changes

2020-07-20 10:15 UTC, merged