Support packaging in upstream repository
upgrades-migrations/preupgrade-assistant-modules pull request #3
Opened 2017-08-11 10:57 UTC by pirat89

Added SPEC file for preupgrade-assistant-el6toel7 package. It needs
archive with usual name
    preupgrade-assistant-el6toel7-%{version}-%{release}.tar.gz

Archive can be created and uploaded on github for expected release
as asset file by the release.sh script. The scripts helps create
even releases in case the tag for release is set.

TODO: modify text before merge

2017-08-11 12:47 UTC, bocekm requested changes

2017-08-11 12:47 UTC, bocekm commented on packaging/preupgrade-assistant-el6toel7.spec
> +Summary:        Set of contents created for upgrade to Red Hat Enterprise Linux 7
Use **modules** instead of contents throughout the whole spec.

2017-08-11 12:47 UTC, bocekm commented on packaging/preupgrade-assistant-el6toel7.spec
> +# Why those requirements?
If you don't know, just delete them and see whether the packaging works.

2017-08-11 12:47 UTC, bocekm commented on packaging/release.sh
> +    msg+="\n    $ go build github.com/aktau/github-release"
Add an info about the need for GitHub token.
`export GITHUB_TOKEN=...`

2017-08-15 13:45 UTC, bocekm submitted a review, later dismissed

2017-08-15 14:15 UTC, pirat89 commented
--test--

2017-08-16 11:52 UTC, bocekm approved these changes

2017-08-16 12:03 UTC, merged