Support for assessment format version
upgrades-migrations/preupgrade-assistant-modules pull request #32
Opened 2017-10-27 09:06 UTC by pirat89

We want to assume that other tools will be able to "understand"
output data. For this purpose modules will provide a new key inside
the properties.ini file: "ast_fmt_version". This will contain version
in X.Y format, with semantic:
 - X will be bumped, when "something" has been changed or removed,
     so other tools need to be checked, whether they are still
     compatible with modules or not
 - Y will be bumped, when just "something" new has been added, but
     tools should be still compatible with current version

The "something" will be specified later in docs. Currently we can
say, that it is everything, that is parsed, read, required by other
tools for their correct functionality, but it doesn't include e.g.
  specific pre-upgrade scripts
  specific post-upgrade scripts
  parts of outputs in reports
  ...
But we can say, that it includes e.g.:
  dirtyconf directory
  hooks directory
  kickstart/RHRHEL7rpmlist_replaced file; that is used when kickstart
                                          is generated
  ...

Resolves #31

2017-10-27 09:08 UTC, pirat89 commented
Note: do not merge this yet

2017-10-27 09:33 UTC, jmazanek submitted a review, later dismissed
I agree with the suggested concept of version control as such. 
Perhaps the name of the new .ini file directive should be more intuitive. But this should not be a big issue, as long as it is well explained in the documentation.

2017-10-27 10:33 UTC, bocekm requested changes

2017-10-27 10:33 UTC, bocekm commented on RHEL6_7/properties.ini
> +ast_fmt_version=0.1
`ast` is really bad abbreviation IMO. Come up with a name that quickly gives you the idea what it stores. I couldn't figure out what the `ast` could mean.
I vote for `assessment_format_version` or (if you like shorter names; P.S. I don't) `assessment_fmt_ver`.

2017-11-01 19:32 UTC, AloisMahdal commented
Just note about the versioning strategy; what I've suggested in issue #31 is actually much simpler than OP:

 *  SemVer but only `major.minor` (no `.patch`),
 *  and while version is `0.*`, we don't have to distinguish between "small" and "big"
    updates.

IOW, we will simply bump the `minor` number with *any* change.  (Note that since the only supported workflow is to always re-run assessment right before upgrade, we should never need to support multiple versions.)

Once we are confident we have stable specifications and reasonable coverage tests (that can be wayyy down in future, if we ever reach that point), we can bump to `1.0` and start applying the rules properly.

2017-11-01 22:09 UTC, pirat89 commented
@bocekm: Done :-)

2017-11-02 13:37 UTC, bocekm approved these changes

2017-11-03 13:37 UTC, pirat89 commented
Closing the PR as after discussion this does not seem relevant. The version of format of assessment will by specified by preupgrade-assistant. Not by modules.

2017-11-03 13:37 UTC, closed without merging